### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by luanmuniz** [evilmartians/lefthook#164]
I see that there is no commit since Oct 2020 and the last version in May 2020.
I really like this project, but if no one is maintaining can't introduce it to any company.

**Comment by muuvmuuv** [comment]
Just because there is not much activity does not mean it is not stable to use or cannot be used in a company... rl always comes first btw., but yes, it just got recently transferred to @evilmartians, so you can be sure it will slowly get a new start.

> https://github.com/evilmartians/lefthook/commit/37a7fe9af0ac2f18e85ee0b9e1cb6a2bd6d9ad1e

**Comment by Envek** [comment]
As it is said in 37a7fe9, Lefthook wasn't maintained for some time as its original creator is quite busy for a while, so we moved repo under our organization's control to ease contributing for other Martians.

We don't have detailed plans for further development of the tool now, but we will maintain it because many of our projects rely on it. And we like it, after all.

So, **yes, it is maintained**.

By the way, [v0.7.3](https://github.com/evilmartians/lefthook/releases/tag/v0.7.3) was just released :wink:
