### ISSUE TITLE
Support LFS internally

### ISSUE THREAD

**Issue by muuvmuuv** [evilmartians/lefthook#276]
Repositories using git-lfs have some kind of problem that lfs just hangs when using it as a command in lefthook. Manually patching the hooks file temporary fixes the issue with some kind of post-checkout command, but doesn't fix it.

I suggest to pull in git-lfs as a go-mod and run it directly if a gitattributes with lfs is installed. LFS would then not be required in path anymore, since it's bundled with lefthook, which also gives a performance benefit. But any other implementation is also fine.

More research about lfs detection should be made. [Githooks](https://github.com/gabyx/Githooks) for example [already use it internally](https://github.com/gabyx/Githooks/blob/8025718df966574e12485ecdb8bbe5b6ffd050f1/githooks/apps/runner/runner.go#L379-L409).

Rel: https://github.com/evilmartians/lefthook/issues/55 (created a new issue, since owners have changed)

```yaml
post-commit:
  commands:
    lfs:
      run: git lfs post-commit {0} # hangs – does not work
```

**Comment by mrexox** [comment]
Thank you for the issue! This is a good feature to have. We are planning to release version 1.0.0 soon which aims to reorganizing the code and refactoring. We will start working on this feature in the following release (might be 1.1.0).

**Comment by mrexox** [comment]
Hey @muuvmuuv! I have prepared a PR to support Git LFS: https://github.com/evilmartians/lefthook/pull/306. Thank you for the reference to Githooks. There is a small nuance here:

`git lfs pre-push` reads from STDIN (see [man page](https://www.mankier.com/1/git-lfs-pre-push)). This behavior is a breaking change in how lefthook is expected to be used, because initially we don't require any input from the CLI. Of course we could add some fields to support automation but I am not sure the game is worth the candle. What do you think about it? Do you expect a full support of `git lfs pre-push`?

**Comment by muuvmuuv** [comment]
Awesome! I don't think this is needed, if it works for hooks, fine.

**Comment by mrexox** [comment]
Nice! I am going to release 1.1.0 soon (in about a week).
