### ISSUE TITLE
`lefthook install` does not seem to recreate .git/hooks if it has been deleted

### ISSUE THREAD

**Issue by technicalpickles** [evilmartians/lefthook#571]
### :wrench: Summary

I'm working on moving us from another git hook tool to lefthook, so I've been testing how the git hooks get setup so I can make sure it works consistently. In doing that, I end up doing `rm -r .git/hooks` quite a bit.

I would have expected `lefthook install` to do that, but instead it exits silently and successfully. If I do `lefthook install --force`, it does not recreate the files

### Lefthook version

1.5.2

### Steps to reproduce

- `lefthook install`
- configure a simple pre-commit hook:
```yaml
pre-commit:
  commands:
    echo:
      run: echo echo
```
- `lefthook install`
- `rm .git/hooks/*`
- `lefthook install`

### Expected results

For the last lefthook after the rm:

```
❯ lefthook install
sync hooks: ✔️ (pre-commit)
```

### Actual results

```
❯ lefthook install
```

### Possible Solution

I _think_ it has to do with doing a checksum of the lefthook configuration. If I make any changes, it does seem to work as expected.

### Logs / Screenshots

```bash
LEFTHOOK_VERBOSE=true git ...
```

**Comment by mrexox** [comment]
Hey! Lefthook uses special hashsum to determine config file changes. It stores the hashsum to `.git/info/lefthook.checksum`. This is useful to skip re-installing hooks every time you execute the hook because this is how lefthook knows that your config file has changed or not.

But it makes sense to sync the hooks regardless of the changes in the config just because you run it manually. I'll try to fix this next week.
