### ISSUE TITLE
Don't auto-install hooks when using the npm package

### ISSUE THREAD

**Issue by anthonyhayesres** [evilmartians/lefthook#618]
### :zap: Summary

Don't auto install hooks when using the npm package

### Value
I was surprised when the npm auto-installed the lefthook hooks -> I work in a large monorepo, and I can't assert that all users will want or need the hooks. It's not very clearly documented in lefthook that the npm package does this auto-install behaviour.

I have a CI system for validating work, but would still like to version lefthook in my repo -> I'd love a way to opt-out (or opt-in) to the auto install behaviour.

One reason for using the npm package as opposed to say, homebrew, would be to manage new features in lefthook - how do I know my users are using the correct version of lefthook with the lefthook config file I've comitted?

Prior art: husky has an `init` script that will set up a `prepare` script: https://typicode.github.io/husky/get-started.html. It does not auto install by default: https://typicode.github.io/husky/#articles

### Behavior and configuration changes

Breaking change - don't auto install the hooks, following the same philosophy as husky

**Comment by mrexox** [comment]
Hey @anthonyhayesres! Thank you for creating this feature request. This question about auto-install of lefthook is debatable. I agree that auto-installing something from an npm package can be surprising. The intent was to force using git hooks in a project that has explicit dependency specified.

If you want to have optional hooks but want to make sure the user will have appropriate version of lefthook, then you can use [`min_version`](https://github.com/evilmartians/lefthook/blob/master/docs/configuration.md#min_version) setting. I hope that it solves your problem.

I respect the philosophy of husky, but husky is a tool that is distributed only via npm package, while lefthook can be installed with many different ways. That's why the approach was different from the very beginning. If you specify `lefthook` as a dependency, you'll probably want to force git hooks usage, and it can be convenient in case you don't want to worry about making sure all developers properly installed lefthook. But if you want to keep lefthook optional you can only have `lefthook.yml` in the repository and let the enthusiasts use it or not.

In CI lefthook skips auto install if the `CI` variable is set. So, using with CI shouldn't be a problem.

But if you have some problems, please describe them. I don't deny the possibility of a bug here 🤔

**Comment by anthonyhayesres** [comment]
Hey thanks for the quick response! Thanks for highlighting the `min_version` setting - I think the combination of that with installing lefthook manually will work for my use case. 🎉
